// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwpjbpmbkxtosdegijmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3cGpicG1ia3h0b3NkZWdpam10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzUzNDUsImV4cCI6MjA2NDU1MTM0NX0.nEXihc9rwdt0bmHf_FRfO57_3UotfpXNPp9P6OKA2sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);